@startuml

interface Analogic_Input_5 <<Client_Server_Interface>>
{
  Gathers operations allowing to manage a
  analogical hardware input from 0 to 5 volt.
  --
  {abstract} + Get_Voltage( OUT voltage:T_Voltage_5 )

}

@enduml